config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

constraints(:subdomain => 'darasa') do

  root to: 'sites#new' 
  resources :sites
  namespace :api do
  namespace :v1 do
    get 'profile/index'
    end
  end

  resources :campus
  resources :institution_types
  resources :systems
  get 'actvities/unit'

  get 'actvities/topic'

  get 'actvities/question'

  namespace :api do
  namespace :v1 do
    get 'google/google'
    end
  end

  get 'smses/index'

  get 'smses/show'

  get 'smses/destroy'

  get 'user/index'

  get 'user/show'

  get 'purchases/index'

  get 'purchases/show'

  get 'subtopics/index'

  get 'subtopics/show'

  get 'subtopics/edit'

  get 'subtopics/destroy'

  get 'subtopics/new'

  get 'subtopics/create'

  get 'subtopics/update'

  get 'subtopics/destroy'

  namespace :api do
  namespace :v1 do
    post '/sms', :to => 'sms#sms'
    resources :sms
    end
  end

  namespace :api do
    namespace :v1 do
      get 'processpayment/process(:parameters)' , :to => "processpayment#process"
          end
        end
      
        resources :responses
        
        resources :questions
    mount Ckeditor::Engine => '/ckeditor'
    resources :cats
    devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

    mount Sidekiq::Web => '/sidekiq'
    devise_scope :user do
      authenticated :user do
        root 'subtopics#index', as: :authenticated_root
      end
      unauthenticated :user do
        root :to => 'devise/registrations#new', as: :unauthenticated_root
      end
  end

  resources :institutions
  resources :courses
  resources :years
  resources :semesters

  resources :units do
    get :make_available
    get :make_unavailable
  end

  resources :uploads do
    post :process_document, :to => 'uploads#get_questions'
    post :process_questions, :to => 'uploads#process_questions'
  end

  resources :topics do
    member do
      get :download
    end
    get :make_sample
    get :undo_sample
  end

  resources :cats do
    member do
      get :download
    end
  end    

  resources :exams do
    member do
      resources :questions do 
        resources :responses
      end
      get :download
      put :accept_tos
    end
  end

  resources :subtopics do
      resources :questions do 
        resources :responses
    end
    resources :uploads
    post :process_document, :to => 'uploads#get_questions'
    post :process_questions, :to => 'uploads#process_questions'
  end

  
  namespace :api do
    namespace :v1 do

      get  "/subtopics", :to => 'subtopics#index'

      get  "/topics", :to => 'topics#index'
      get "/questions", :to => 'topics#show'

      get "/units", :to => 'units#index'
      get "/units/:id", :to => 'units#show'
      get "/exams", :to => 'exams#index'
      get "/exams/:id", :to => 'exams#show'
      get "/terms", :to => 'terms#show'
      get "/answers", :to => 'exams#answer'

      get "/url", :to => 'url#show'

      get "/auth/facebook_access_token/callback", :to => 'facebook#facebook'
      post "/auth/facebook_access_token/callback", :to => 'facebook#facebook'
      post "/google_sign_up", :to => 'google#google'#, :as => 'register'
      
      post "/pay", :to => 'payments#pay'
      get "/pay", :to => 'payments#show'
      get "/index", :to => 'payments#index'

      get "/user_details", :to => 'details#show_user_details'
      get "/is_owner", :to => 'details#do_i_own_this_topic'
      get "/unit_name", :to => 'details#show_unit' # remove this end point
      get "/my_topics", :to => 'details#my_topics'

      post "/institutions", :to => 'institutions#index'
      post "/campus", :to =>'campus#index'
      post "/courses", :to =>'courses#index'
      post "/types", :to => 'types#index'
      post "/profile", :to => 'profile#index'

      devise_scope :user do
        post"/update", :to => 'registrations#update'
        post "/sign_in", :to => 'sessions#create'
        delete "/sign_out", :to => 'sessions#destroy'
        post "/sign_up", :to => 'registrations#create'#, :as => 'register'
      end
    end
  end

  resources :user do
    get :make_moderator
    get :make_normal_user
    delete 'user/:id' => 'user#destroy', :via => :delete #, :as => :admin_destroy_user
  get 'user/:id' => 'user#show', as: :user
  end

  

  end
end

app/models/institution.rb
# == Schema Information
#
# Table name: institutions
#
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  id         :uuid             not null, primary key
#  deleted_at :datetime
#  country    :string
#  type_id    :uuid
#

class Institution < ActiveRecord::Base
	acts_as_paranoid
	# self.per_page = 10
	has_many :courses, :dependent => :destroy
	has_many :campus, :dependent => :destroy
	has_many :profiles
	has_many :units

	belongs_to :institution_type

	def self.with_type(type_name)
		type  = InstitutionType.where( :type_name => type_name).first
		where(:institution_type_id => type.id)
		
	end
end

app/models/institution_type.rb
# == Schema Information
#
# Table name: types
#
#  id         :integer          not null, primary key
#  type_name  :string
#  system_id  :uuid
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class InstitutionType < ActiveRecord::Base
	acts_as_paranoid
	belongs_to :system
	
	has_many :institutions
	has_many :units, :through => :institutions
	

end

app/controllers/api/v1/institutions_controller.rb
class Api::V1::InstitutionsController < ApplicationController
	skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }

	before_filter :authenticate_user!, except: [:index]
	# byebug
	before_filter :ensure_authentication_token_param_exists, :ensure_type_param_exists

	def index
		resource =  User.find_by_authentication_token(params[:auth_token])
		# byebug
		# byebug
		return invalid_user unless resource

		#********If the use is an admin they can view everything************#
		#****if not, they'll view what we have approved*********####

		if resource.is_admin?
		# if current_user.is_admin?
		  @institutions = Institution.where(:institution_type_id=> params[:type_id])
		  return no_institutions if @institutions.empty?
		else
		  @institutions =  Institution.where(:institution_type_id => params[:type_id])
		   return no_institutions if @institutions.empty?
		end
		
	end



	private

	def ensure_authentication_token_param_exists
	  ensure_param_exists :auth_token
	end

	def ensure_type_param_exists
	  ensure_param_exists :type_id
	end

	def no_institutions
		render json: { success: false, msg: "No institutions!"}, status: :unprocessable_entity
	end

	def invalid_user
	  render json: { success: false, error: "Error with your credentials"}, status: :unauthorized
	end

	def set_csrf_header
	   response.headers['X-CSRF-Token'] = form_authenticity_token
	end

	  # Use callbacks to share common setup or constraints between actions.
	  # def set_institution
	  #   @institution = Institution.includes(:topics).find(params[:id]) #include(:topics) includes all teh topics in that institution pre-emptively, saving alot ot memory and computing resources
	  # end

	  def ensure_param_exists(param)
	    return unless params[param].blank?
	    render json:{ success: false, error: "Missing #{param} parameter"}, status: :unprocessable_entity
	  end

	  # Never trust parameters from the scary internet, only allow the white list through.
	  def institution_params
	    params.require(:institution).permit(:name, :semester_id)
	  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin, only:[:new, :edit, :update, :create, :destroy]
  # before_action :authenticate_user!

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
    @courses = @institution.courses
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.includes(:courses).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:name, :institution_type_id)
    end
end

app/helpers/api/v1/institutions_helper.rb
module Api::V1::InstitutionsHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_form.html.haml
= form_for @institution do |f|
  - if @institution.errors.any?
    #error_explanation
      %h2= "#{pluralize(@institution.errors.count, "error")} prohibited this institution from being saved:"
      %ul
        - @institution.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  
  .field
    =f.select :institution_type_id, InstitutionType.all.map { |t| [t.type_name, t.id]}
  .actions
    = f.submit 'Save'

app/views/institutions/edit.html.haml
%h1 Editing institution

= render 'form'

= link_to 'Show', @institution
\|
= link_to 'Back', institutions_path

app/views/institutions/index.html.haml
%h1 Institutions 
/ =@institution.name

/ %table
/   %thead
/     %tr
/       %th Name
/       %th
/       %th
/       %th

/   %tbody
/     - @institutions.each do |institution|
/       %tr
/         %td= institution.name
/         %td= link_to 'Show', institution
/         %td= link_to 'Edit', edit_institution_path(institution)
/         %td= link_to 'Destroy', institution, :method => :delete, :data => { :confirm => 'Are you sure?' }

/ %br



%table.table.table-hover
  %thead
    %tr
      %th Name
      

  %tbody
    - @institutions.each do |institution|
      %tr
        %td= institution.name
        / %td= link_to institution.course.name, courses_path
        %td
          -if current_user && current_user.is_admin?
            = link_to 'Edit', edit_institution_path(institution)
            = link_to 'Destroy', institution, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

/ =render "courses/table"
.row
  .col-sm-15.col-md-15
    - @institutions.each do |institution|
      .col-sm-6.col-md-4
        .thumbnail
          %img{:alt => "...", :src => "..."}
            .caption
              %h3 #{institution.name}
              %p ...
              %p
                -if current_user && current_user.is_admin?
                  = link_to 'Edit', edit_institution_path(institution), class: "btn btn-primary"
                  = link_to 'Destroy', institution, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-default"                
                  = link_to 'View Courses', institution_path(institution), class: "btn btn-success"
                / %a.btn.btn-primary{:href => "#", :role => "button"} Button
                / %a.btn.btn-default{:href => "#", :role => "button"} Button

/ =@course.institution.name

-if current_user && current_user.is_moderator?
  = link_to 'New Institution', new_institution_path, class: "btn btn-primary"

app/views/institutions/new.html.haml
%h1 New institution

= render 'form'

= link_to 'Back', institutions_path

app/views/institutions/show.html.haml
%h1 Courses for #{@institution.name}

-course_for_this_uni = []

- @courses.each do |course|
	-if course.institution.name == @institution.name 
		-course_for_this_uni << course


-if course_for_this_uni.empty?
	%p
		There are no courses for this institution yet
-else
	=render "courses/table1", courses: course_for_this_uni



-if current_user && current_user.is_admin? || current_user.is_moderator?
	= link_to 'Edit', edit_institution_path(@institution)
	\|
	= link_to 'Back', institutions_path