config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

constraints(:subdomain => 'darasa') do

  root to: 'sites#new' 
  resources :sites
  namespace :api do
  namespace :v1 do
    get 'profile/index'
    end
  end

  resources :campus
  resources :institution_types
  resources :systems
  get 'actvities/unit'

  get 'actvities/topic'

  get 'actvities/question'

  namespace :api do
  namespace :v1 do
    get 'google/google'
    end
  end

  get 'smses/index'

  get 'smses/show'

  get 'smses/destroy'

  get 'user/index'

  get 'user/show'

  get 'purchases/index'

  get 'purchases/show'

  get 'subtopics/index'

  get 'subtopics/show'

  get 'subtopics/edit'

  get 'subtopics/destroy'

  get 'subtopics/new'

  get 'subtopics/create'

  get 'subtopics/update'

  get 'subtopics/destroy'

  namespace :api do
  namespace :v1 do
    post '/sms', :to => 'sms#sms'
    resources :sms
    end
  end

  namespace :api do
    namespace :v1 do
      get 'processpayment/process(:parameters)' , :to => "processpayment#process"
          end
        end
      
        resources :responses
        
        resources :questions
    mount Ckeditor::Engine => '/ckeditor'
    resources :cats
    devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

    mount Sidekiq::Web => '/sidekiq'
    devise_scope :user do
      authenticated :user do
        root 'subtopics#index', as: :authenticated_root
      end
      unauthenticated :user do
        root :to => 'devise/registrations#new', as: :unauthenticated_root
      end
  end

  resources :institutions
  resources :courses
  resources :years
  resources :semesters

  resources :units do
    get :make_available
    get :make_unavailable
  end

  resources :uploads do
    post :process_document, :to => 'uploads#get_questions'
    post :process_questions, :to => 'uploads#process_questions'
  end

  resources :topics do
    member do
      get :download
    end
    get :make_sample
    get :undo_sample
  end

  resources :cats do
    member do
      get :download
    end
  end    

  resources :exams do
    member do
      resources :questions do 
        resources :responses
      end
      get :download
      put :accept_tos
    end
  end

  resources :subtopics do
      resources :questions do 
        resources :responses
    end
    resources :uploads
    post :process_document, :to => 'uploads#get_questions'
    post :process_questions, :to => 'uploads#process_questions'
  end

  
  namespace :api do
    namespace :v1 do

      get  "/subtopics", :to => 'subtopics#index'

      get  "/topics", :to => 'topics#index'
      get "/questions", :to => 'topics#show'

      get "/units", :to => 'units#index'
      get "/units/:id", :to => 'units#show'
      get "/exams", :to => 'exams#index'
      get "/exams/:id", :to => 'exams#show'
      get "/terms", :to => 'terms#show'
      get "/answers", :to => 'exams#answer'

      get "/url", :to => 'url#show'

      get "/auth/facebook_access_token/callback", :to => 'facebook#facebook'
      post "/auth/facebook_access_token/callback", :to => 'facebook#facebook'
      post "/google_sign_up", :to => 'google#google'#, :as => 'register'
      
      post "/pay", :to => 'payments#pay'
      get "/pay", :to => 'payments#show'
      get "/index", :to => 'payments#index'

      get "/user_details", :to => 'details#show_user_details'
      get "/is_owner", :to => 'details#do_i_own_this_topic'
      get "/unit_name", :to => 'details#show_unit' # remove this end point
      get "/my_topics", :to => 'details#my_topics'

      post "/institutions", :to => 'institutions#index'
      post "/campus", :to =>'campus#index'
      post "/courses", :to =>'courses#index'
      post "/types", :to => 'types#index'
      post "/profile", :to => 'profile#index'

      devise_scope :user do
        post"/update", :to => 'registrations#update'
        post "/sign_in", :to => 'sessions#create'
        delete "/sign_out", :to => 'sessions#destroy'
        post "/sign_up", :to => 'registrations#create'#, :as => 'register'
      end
    end
  end

  resources :user do
    get :make_moderator
    get :make_normal_user
    delete 'user/:id' => 'user#destroy', :via => :delete #, :as => :admin_destroy_user
  get 'user/:id' => 'user#show', as: :user
  end

  

  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  email                  :string           not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  first_name             :string
#  phone_number           :string
#  university             :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  second_name            :string
#  terms                  :boolean          default(FALSE)
#  provider               :string
#  uid                    :string
#  role_id                :integer
#  terms_updated_at       :datetime
#  authentication_token   :text
#  id                     :uuid             not null, primary key
#  unique_session_id      :string(20)
#  last_seen_at           :datetime
#  last_seen              :datetime
#  deleted_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_paranoid
  before_save :ensure_authentication_token
    belongs_to :role
    before_create :set_default_role
  devise :database_authenticatable, :lastseenable, :registerable, :session_limitable,:token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2, :facebook]
  # validates_acceptance_of :tos_agreement, :allow_nil => true, :accept => true, :on => :create
  has_many :payments, dependent: :destroy
  has_many :purchases, dependent: :destroy
  has_many :failed_payments, dependent: :destroy

  #lOGGIN USER ACTIVITIES
  has_many :unit_activities, dependent: :destroy
  has_many :topic_activities, dependent: :destroy
  has_many :question_activities, dependent: :destroy
  has_many :payment_activities, dependent: :destroy

  has_one :profile, dependent: :destroy



	def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
		# byebug
		data = access_token.info
		# byebug
		user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
		if user
			return user
		else
			registered_user = User.where(:email => access_token.info.email).first
				if registered_user
					return registered_user
				else
					user = User.create(first_name: data["first_name"], second_name: data["last_name"],
						provider:access_token.provider,
						email: data["email"],
						uid: access_token.uid ,
						password: Devise.friendly_token[0,20],
					)
				end
		end
	end

	def ensure_authentication_token
		if authentication_token.blank?
			self.authentication_token = generate_authentication_token
	 	end
	end

	def check_user_role
		if is_moderator?
			accept_terms
		end
	end
	#check if the user has accepted terms and conditions. By defauts, it's false
	def accept_terms
		self.terms
	end

	def is_admin?
		if self.role.nil?
			false
		elsif self.role.name == "admin"
			true
		else
			false
		end
	end
	
	#if the user has not accepted terms and conditions, they are not a moderator!
	def is_moderator?
		# if accept_terms
		# 	if self.role.nil? #they could be an admin!
		# 		make_moderator
		# 	elsif
		# 		self.role.name =='moderator'
		# 		true
		# 	else
		# 		false
		# 	end
		# else
		# 	false
		# end
		if self.role.nil?
			false
		elsif self.role.name == "moderator"
			true
		else
			false
		end
	end

	def has_admin_previlages?
		if is_admin? || is_moderator?
			# if is_moderator?
			# 	 p "Yes moderator"
			# 	 true
			# elsif is_admin?
			# 	 "Yes Admin"
			# end
			true
		else
			false
		end
	end

	def agree_tos
		self.update_attributes :terms => true, :terms_updated_at => Time.now
		make_moderator
	end

	def make_moderator
		self.update_attributes :role_id => 3
		# self.role ||= Role.find_by_name('moderator') 
	end

	def make_admin
		self.update_attributes :role_id => 4
	end

	def make_normal_user
		self.update_attributes :role_id => 1
	end

	def show_admins
		User.where(:role_id => 4 )
	end

	#checking if the user has paid to view the answers

	def has_paid? topic_id
		if self.payments.first.nil? #check if there's a payment record, before we do a look up in the db will save us some time :-)
			check_if_this_unit_is_paid_for topic_id
		else
			check_if_this_unit_is_paid_for topic_id # have you really paid fro this unit?
		end
	end

	def owns? topic_id
		if self.purchases.first.nil?
			false
		else
			check_if_topic_is_in_my_assets topic_id
		end
	end

	private
	# Making all users' role to be registered as they sign up.
	def set_default_role
		self.role ||= Role.find_by_name('registered') 
	end

	def generate_authentication_token
		loop do
			token = Devise.friendly_token
			break token unless User.where(authentication_token: token).first
		end
	end
	def empty?
		self.empty?
	end

	def check_if_topic_is_in_my_assets topic_id
		@assets = self.purchases
		if @assets.find_by_topic_id(topic_id).nil?
			false
		else
			true
		end
	end



	def check_if_this_unit_is_paid_for topic_id
		@payment = self.payments
		if @payment.present? #has the user made any Payments?
			if @payment.find_by_topic_id(topic_id).nil? #If not no need to check further!
				false
			else
				true
			end
		else
			false
		end
	end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  	@users = User.all.order(created_at: :desc)
  end

  def show
  	@user = User.find(params[:id])
    @failed_payments = @user.failed_payments
  end

  def make_moderator
    @user = User.find(params[:user_id])
    @user.make_moderator
    respond_to do |format|
      format.html { redirect_to user_index_path, notice:  " #{@user.first_name} is now a Moderator." }
      format.json { head :no_content }
    end
  end
  def make_normal_user
    @user = User.find(params[:user_id])
    @user.make_normal_user
    respond_to do |format|
      format.html { redirect_to user_index_path, notice:  " #{@user.first_name} is now a Normal User." }
      format.json { head :no_content }
    end
  end



  def destroy
  	@user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to user_index_path, notice:  " #{@user.first_name} was successfully destroyed." }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_table.html.haml
.row
  .span6
    - Time.zone = 'Nairobi'
  /   = line_chart User.group_by_day(:created_at).count
  / .span6
  /   = line_chart User.group_by_day(:created_at).count
.container
  .row-fluid
    .col-xs-12.col-sm-6.col-md-6
      .well.well-sm
        .row
          .col-sm-6.col-md-8
            %h4
              %p User signups
        = line_chart User.group_by_day(:created_at).count

  .row-fluid
    .col-xs-12.col-sm-6.col-md-6
      .well.well-sm
        .row
          .col-sm-6.col-md-8
            %h4
              %p Unit Activities Today
        = pie_chart  UnitActivity.group_by_hour_of_day(:created_at, range: 1.day.ago..Time.now).count


%table.table.table-hover
  %thead
    %tr
      %th First Name
      %th Last Name
      %th Email
      %th Phone Number
      %th Since Sign up it has been
      %th Topics bought
      %th

  %tbody
    - users.each do |user|
      %tr
        %td= user.first_name
        %td= user.second_name
        %td= user.email
        %td= user.phone_number
        - from_time = user.created_at
        %td= time_ago_in_words(from_time)
        %td 
          %span.label.label-default.label-pill.pull-xs-right  #{user.purchases.count} 
        %td
          -if current_user && current_user.is_admin?
            = link_to 'Show Details',  user, class: "label label-warning"
            = link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "label label-danger"
            -unless current_user == user
              -if user.is_moderator?
                = link_to " Moderator - Make Normal user", user_make_normal_user_path(user), class: "label label-pill label-default"
              -elsif user.is_admin?
                = link_to " Admin Make Normal user",  user_make_normal_user_path(user), :data => { :confirm => 'Are you sure?' }, class: "label label-pill label-info"
              -else
                = link_to "Make moderator", user_make_moderator_path(user), :data => { :confirm => 'Are you sure?' }, class: "label label-success"

app/views/user/index.html.haml
%h1 We have a total of #{@users.all.count} Users


=render "user/table", users: @users

app/views/user/show.html.haml
%h1 #{@user.first_name} #{@user.second_name} Darasa Activities
- Time.zone = 'Nairobi'
.container
	.row-fluid
		.col-xs-12.col-sm-6.col-md-6
			.well.well-sm
				.row
					.col-sm-6.col-md-4
						/ %p= image_tag @user.attachment_url(:large), height: "200", class: "img.img-rounded.img-responsive"
					.col-sm-6.col-md-8
						%h4
							%p #{@user.first_name} #{@user.second_name}
						%p
							%p #{@user.email} ,  #{@user.phone_number}
						%small
							%cite{:title => "Unit Code"}
								%p #{@user.phone_number}
						%p
							%i.glyphicon.glyphicon-usd
							Number of Payments made  #{@user.payments.count}
							%br/
							%i.glyphicon.glyphicon-thumbs-up
							Number of Purchases made  #{@user.purchases.count}
							%br/
							%i.glyphicon.glyphicon-thumbs-down
							Number of failed Payments  #{@user.failed_payments.count}
						/ Split button
						-if current_user && current_user.is_admin?
							/ Topics owned
						/ %ul 
						/ 	- @user.purchases.each do |purchase|
						/ 		%li	
						/ 			#{purchase.topic.name}
						/ = link_to 'Edit', edit_topic_path(@user), class: "btn btn-primary"
						= link_to 'Back',  user_index_path, class: "btn btn-default"
						.btn-group.dropup
							%button.btn.btn-primary{:type => "button"}
								Topics owned
							%button.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
								%span.caret
								%span.sr-only Social
							%ul.dropdown-menu{:role => "menu"}
								- @user.purchases.each do |purchase|
									%li	
										#{purchase.topic.name}
	.row-fluid
		.col-xs-12.col-sm-6.col-md-6
			.well.well-sm
				.row
					.col-sm-6.col-md-8
						%h4
							%p Units that #{@user.first_name} clicked
				= pie_chart @user.unit_activities.group(:name).count
.container
	.row-fluid
		.col-xs-12.col-sm-6.col-md-6
			.well.well-sm
				.row
					.col-sm-6.col-md-8
						%h4
							%p Topics that #{@user.first_name} clicked
				= pie_chart @user.topic_activities.group(:name).count
				

	.row-fluid
		.col-xs-12.col-sm-6.col-md-6
			.well.well-sm
				.row
					.col-sm-6.col-md-8
						%h4
							%p Questions that #{@user.first_name} clicked
				= pie_chart @user.question_activities.group(:question_id).count

	.row-fluid
		.col-xs-12.col-sm-6.col-md-6
			.well.well-sm
				.row
					.col-sm-6.col-md-8
						%h4
							%p Topics that #{@user.first_name} attempted to purchase
				= pie_chart @user.payment_activities.group(:name).count

	.row-fluid
		.col-xs-12.col-sm-6.col-md-6
			.well.well-sm
				.row
					.col-sm-6.col-md-8
						%h4
							%p Failed Payments for #{@user.first_name} 
				= pie_chart @user.failed_payments.group(:topic_id).count


%h1 #{@user.first_name}  #{@user.second_name}  Failed Payment Details

%table.table.table-hover
	%thead
		%tr
		%th Topic
		%th Unit
		%th Institution
		%th Mpesa Code
		%th Time

	%tbody
		- @failed_payments.each do |payment|
			%tr
				%td= payment.topic.name
				%td= payment.topic.unit.name
				%td= payment.topic.unit.institution.name
				%td= payment.mpesa_code
				%td= payment.created_at.strftime("%b %d, %Y %A  %l:%M%P")