config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

constraints(:subdomain => 'darasa') do

  root to: 'sites#new' 
  resources :sites
  namespace :api do
  namespace :v1 do
    get 'profile/index'
    end
  end

  resources :campus
  resources :institution_types
  resources :systems
  get 'actvities/unit'

  get 'actvities/topic'

  get 'actvities/question'

  namespace :api do
  namespace :v1 do
    get 'google/google'
    end
  end

  get 'smses/index'

  get 'smses/show'

  get 'smses/destroy'

  get 'user/index'

  get 'user/show'

  get 'purchases/index'

  get 'purchases/show'

  get 'subtopics/index'

  get 'subtopics/show'

  get 'subtopics/edit'

  get 'subtopics/destroy'

  get 'subtopics/new'

  get 'subtopics/create'

  get 'subtopics/update'

  get 'subtopics/destroy'

  namespace :api do
  namespace :v1 do
    post '/sms', :to => 'sms#sms'
    resources :sms
    end
  end

  namespace :api do
    namespace :v1 do
      get 'processpayment/process(:parameters)' , :to => "processpayment#process"
          end
        end
      
        resources :responses
        
        resources :questions
    mount Ckeditor::Engine => '/ckeditor'
    resources :cats
    devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

    mount Sidekiq::Web => '/sidekiq'
    devise_scope :user do
      authenticated :user do
        root 'subtopics#index', as: :authenticated_root
      end
      unauthenticated :user do
        root :to => 'devise/registrations#new', as: :unauthenticated_root
      end
  end

  resources :institutions
  resources :courses
  resources :years
  resources :semesters

  resources :units do
    get :make_available
    get :make_unavailable
  end

  resources :uploads do
    post :process_document, :to => 'uploads#get_questions'
    post :process_questions, :to => 'uploads#process_questions'
  end

  resources :topics do
    member do
      get :download
    end
    get :make_sample
    get :undo_sample
  end

  resources :cats do
    member do
      get :download
    end
  end    

  resources :exams do
    member do
      resources :questions do 
        resources :responses
      end
      get :download
      put :accept_tos
    end
  end

  resources :subtopics do
      resources :questions do 
        resources :responses
    end
    resources :uploads
    post :process_document, :to => 'uploads#get_questions'
    post :process_questions, :to => 'uploads#process_questions'
  end

  
  namespace :api do
    namespace :v1 do

      get  "/subtopics", :to => 'subtopics#index'

      get  "/topics", :to => 'topics#index'
      get "/questions", :to => 'topics#show'

      get "/units", :to => 'units#index'
      get "/units/:id", :to => 'units#show'
      get "/exams", :to => 'exams#index'
      get "/exams/:id", :to => 'exams#show'
      get "/terms", :to => 'terms#show'
      get "/answers", :to => 'exams#answer'

      get "/url", :to => 'url#show'

      get "/auth/facebook_access_token/callback", :to => 'facebook#facebook'
      post "/auth/facebook_access_token/callback", :to => 'facebook#facebook'
      post "/google_sign_up", :to => 'google#google'#, :as => 'register'
      
      post "/pay", :to => 'payments#pay'
      get "/pay", :to => 'payments#show'
      get "/index", :to => 'payments#index'

      get "/user_details", :to => 'details#show_user_details'
      get "/is_owner", :to => 'details#do_i_own_this_topic'
      get "/unit_name", :to => 'details#show_unit' # remove this end point
      get "/my_topics", :to => 'details#my_topics'

      post "/institutions", :to => 'institutions#index'
      post "/campus", :to =>'campus#index'
      post "/courses", :to =>'courses#index'
      post "/types", :to => 'types#index'
      post "/profile", :to => 'profile#index'

      devise_scope :user do
        post"/update", :to => 'registrations#update'
        post "/sign_in", :to => 'sessions#create'
        delete "/sign_out", :to => 'sessions#destroy'
        post "/sign_up", :to => 'registrations#create'#, :as => 'register'
      end
    end
  end

  resources :user do
    get :make_moderator
    get :make_normal_user
    delete 'user/:id' => 'user#destroy', :via => :delete #, :as => :admin_destroy_user
  get 'user/:id' => 'user#show', as: :user
  end

  

  end
end

app/models/unit.rb
# == Schema Information
#
# Table name: units
#
#  name          :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  answers_price :float
#  videos_price  :float
#  id            :uuid             not null, primary key
#  semester_id   :uuid
#  price_id      :uuid
#  available     :boolean          default(FALSE)
#  deleted_at    :datetime
#

class Unit < ActiveRecord::Base
	acts_as_paranoid
	has_many :topics,:dependent => :destroy
	belongs_to :semester
	# has_many :cats
	has_many :exams, :dependent => :destroy
	belongs_to :price

	belongs_to :institution
	
	#lOGGIN USER ACTIVITIES
	has_many :unit_activities, :dependent => :destroy

	self.per_page = 10
	

	def all_units
		Unit.all.each do |unit|
			p "#{unit.name} || #{unit.id} "
		end
	end

	def make_unavailable 
		self.update_attribute(:available, false)
	end

	def make_available 
		self.update_attribute(:available, true)
	end

end

app/controllers/api/v1/units_controller.rb
class Api::V1::UnitsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }
  respond_to :json

  # GET api/v1/units
  # GET api/v1/units.json
  def index

    resource =  User.find_by_authentication_token(params[:auth_token])
    # byebug
    return invalid_user unless resource

    #********If the use is an admin they can view everything************#
    #****if not, they'll view what we have approved*********####

    if resource.is_admin?
      @units = Unit.all
    else
      # @units =   Unit.where(:available => :true, :institution_id => "#{resource.profile.institution_id}")
      institution =  Institution.find(resource.profile.institution_id).institution_type_id 
      @units  = InstitutionType.find(institution).units.where(:available => true)
    end
    # @semesters = Semester.all #II need to look into this.
  end

  # GET /units/1
  # GET /units/1.json
  def show
     resource =  User.find_by_authentication_token(params[:auth_token])
     return invalid_user unless resource

     @unit = Unit.find(params[:id])
 
  end



  private

  def ensure_authentication_token_param_exists
    ensure_param_exists :authentication_token
  end

  def invalid_user
    render json: { success: false, error: "Error with your credentials"}, status: :unauthorized
  end

  def set_csrf_header
     response.headers['X-CSRF-Token'] = form_authenticity_token
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.includes(:topics).find(params[:id]) #include(:topics) includes all teh topics in that unit pre-emptively, saving alot ot memory and computing resources
    end

    def ensure_param_exists(param)
      return unless params[param].blank?
      render json:{ success: false, error: "Missing #{param} parameter"}, status: :unprocessable_entity
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :semester_id)
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin, only:[:new, :edit, :update, :create, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.order('created_at ASC').page(params[:page])
    # @semesters = Semester.all #II need to look into this.

  end

  # GET /units/1
  # GET /units/1.json
  def show

     @unit = Unit.find(params[:id])
    @topics = @unit.topics
    

    
     @unit.topics.each do |topic|
      topic.subtopics.each do |subtopic|
        subtopic.questions.each do |question|
              @questions = subtopic.questions.order('created_at ASC').page(params[:page])
            end
          end
        end

    # questions = Question.order('created_at ASC').page(params[:page])
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
   # @semesters = Semester.all #II need to look into this.
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to units_url, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   def make_available
      @unit = Unit.find(params[:unit_id])

      @unit.make_available
      respond_to do |format|
        format.html { redirect_to units_url, notice: "Unit #{@unit.name} is now available" }
        format.json { head :no_content }
      end
   end

   def make_unavailable
       @unit = Unit.find(params[:unit_id])

       @unit.make_unavailable
       respond_to do |format|
         format.html { redirect_to units_url, notice: "Unit  #{@unit.name} is now unavailable" }
         format.json { head :no_content }
       end
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.includes(:topics).find(params[:id]) #include(:topics) includes all teh topics in that unit pre-emptively, saving alot ot memory and computing resources
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :semester_id,:price_id, :institution_id)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.haml
= form_for @unit do |f|
  - if @unit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@unit.errors.count, "error")} prohibited this unit from being saved:"
      %ul
        - @unit.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    =f.label :Semester
    =f.select :semester_id, Semester.all.map { |s| [s.name, s.id]}
  .field
    = f.label :price
    = f.select :price_id, Price.all.map {|p| [p.content, p.id]}
  .field
    = f.label :Institution
    = f.select :institution_id, Institution.all.map {|i| [i.name, i.id]}

  .actions
    = f.submit 'Save'

app/views/units/_table.html.haml
%table.table.table-hover
  %thead
    %tr
      %th Name
      %th Institution
      %th Availability
      

  %tbody
    - units.each do |unit|
      %tr
        %td= unit.name
        %td= unit.institution.name
        %td
          -if unit.available?
            %p.text-success Available
          -else
            %p.text-default  Unavailable
        %td
          -if current_user && current_user.is_admin?
            = link_to 'Edit', edit_unit_path(unit), class: "label label-pill label-default"
            = link_to 'Destroy', unit, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "label label-pill label-danger"
            = link_to 'Show', unit, class: "label label-pill label-warning"
            -if unit.available?
              = link_to " Make Unavailable", unit_make_unavailable_path(unit), class: "label label-pill label-default"            
            -else
              = link_to "Make Available", unit_make_available_path(unit), :data => { :confirm => 'Are you sure?' }, class: "label label-success"
          -elsif current_user && current_user.is_moderator?
            = link_to 'Edit', edit_unit_path(unit), class: "label label-pill label-default"
            = link_to 'Show', unit, class: "label label-pill label-warning"
%br
= will_paginate units, renderer: BootstrapPagination::Rails

app/views/units/edit.html.haml
%h1 Editing unit

= render 'form'

= link_to 'Show', @unit, class: "btn btn-primary"
\|
= link_to 'Back', units_path, class: "btn btn-primary"

app/views/units/index.html.haml
%h1 Listing units

=render "units/table", units: @units #extracted the table from here to a helper

-if current_user && current_user.is_moderator? || current_user.is_admin?
	= link_to 'New Unit', new_unit_path, class: "btn btn-primary"

app/views/units/new.html.haml
%h1 New unit

= render 'form'

= link_to 'Back', units_path, class: "btn btn-primary"

app/views/units/show.html.haml
%h1 Questions for this Unit #{@unit.name}


-if @questions.nil?
	%p
		There are no Questions for this Unit yet
		
-else

	=render "questions/table", questions: @questions#the table that was previously here was extracted to the partial to be DRY. seems like I needed it more than I thought! :-)