config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

constraints(:subdomain => 'darasa') do

  root to: 'sites#new' 
  resources :sites
  namespace :api do
  namespace :v1 do
    get 'profile/index'
    end
  end

  resources :campus
  resources :institution_types
  resources :systems
  get 'actvities/unit'

  get 'actvities/topic'

  get 'actvities/question'

  namespace :api do
  namespace :v1 do
    get 'google/google'
    end
  end

  get 'smses/index'

  get 'smses/show'

  get 'smses/destroy'

  get 'user/index'

  get 'user/show'

  get 'purchases/index'

  get 'purchases/show'

  get 'subtopics/index'

  get 'subtopics/show'

  get 'subtopics/edit'

  get 'subtopics/destroy'

  get 'subtopics/new'

  get 'subtopics/create'

  get 'subtopics/update'

  get 'subtopics/destroy'

  namespace :api do
  namespace :v1 do
    post '/sms', :to => 'sms#sms'
    resources :sms
    end
  end

  namespace :api do
    namespace :v1 do
      get 'processpayment/process(:parameters)' , :to => "processpayment#process"
          end
        end
      
        resources :responses
        
        resources :questions
    mount Ckeditor::Engine => '/ckeditor'
    resources :cats
    devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

    mount Sidekiq::Web => '/sidekiq'
    devise_scope :user do
      authenticated :user do
        root 'subtopics#index', as: :authenticated_root
      end
      unauthenticated :user do
        root :to => 'devise/registrations#new', as: :unauthenticated_root
      end
  end

  resources :institutions
  resources :courses
  resources :years
  resources :semesters

  resources :units do
    get :make_available
    get :make_unavailable
  end

  resources :uploads do
    post :process_document, :to => 'uploads#get_questions'
    post :process_questions, :to => 'uploads#process_questions'
  end

  resources :topics do
    member do
      get :download
    end
    get :make_sample
    get :undo_sample
  end

  resources :cats do
    member do
      get :download
    end
  end    

  resources :exams do
    member do
      resources :questions do 
        resources :responses
      end
      get :download
      put :accept_tos
    end
  end

  resources :subtopics do
      resources :questions do 
        resources :responses
    end
    resources :uploads
    post :process_document, :to => 'uploads#get_questions'
    post :process_questions, :to => 'uploads#process_questions'
  end

  
  namespace :api do
    namespace :v1 do

      get  "/subtopics", :to => 'subtopics#index'

      get  "/topics", :to => 'topics#index'
      get "/questions", :to => 'topics#show'

      get "/units", :to => 'units#index'
      get "/units/:id", :to => 'units#show'
      get "/exams", :to => 'exams#index'
      get "/exams/:id", :to => 'exams#show'
      get "/terms", :to => 'terms#show'
      get "/answers", :to => 'exams#answer'

      get "/url", :to => 'url#show'

      get "/auth/facebook_access_token/callback", :to => 'facebook#facebook'
      post "/auth/facebook_access_token/callback", :to => 'facebook#facebook'
      post "/google_sign_up", :to => 'google#google'#, :as => 'register'
      
      post "/pay", :to => 'payments#pay'
      get "/pay", :to => 'payments#show'
      get "/index", :to => 'payments#index'

      get "/user_details", :to => 'details#show_user_details'
      get "/is_owner", :to => 'details#do_i_own_this_topic'
      get "/unit_name", :to => 'details#show_unit' # remove this end point
      get "/my_topics", :to => 'details#my_topics'

      post "/institutions", :to => 'institutions#index'
      post "/campus", :to =>'campus#index'
      post "/courses", :to =>'courses#index'
      post "/types", :to => 'types#index'
      post "/profile", :to => 'profile#index'

      devise_scope :user do
        post"/update", :to => 'registrations#update'
        post "/sign_in", :to => 'sessions#create'
        delete "/sign_out", :to => 'sessions#destroy'
        post "/sign_up", :to => 'registrations#create'#, :as => 'register'
      end
    end
  end

  resources :user do
    get :make_moderator
    get :make_normal_user
    delete 'user/:id' => 'user#destroy', :via => :delete #, :as => :admin_destroy_user
  get 'user/:id' => 'user#show', as: :user
  end

  

  end
end

app/models/exam.rb
# == Schema Information
#
# Table name: exams
#
#  title      :string
#  attachment :string
#  date       :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  question   :text
#  id         :uuid             not null, primary key
#  unit_id    :uuid
#

class Exam < ActiveRecord::Base
	require 'json'

	# mount_uploader :attachment, PdfUploader #mount the pdf uploader

	validates_presence_of :title, :date, :unit 

	belongs_to :unit

	has_many :questions, :dependent => :destroy

	has_many :answers, :through => :questions

	accepts_nested_attributes_for :questions,  :allow_destroy => true



end

app/controllers/api/v1/exams_controller.rb
class Api::V1::ExamsController < ApplicationController
	# before_filter :authenticate_user!
	# byebug
	before_filter :authenticate_user! , except: [:answer]
	before_filter :ensure_question_id_exists, only: [:answer]
	before_filter :ensure_token_exists
	skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }
	respond_to :json
	 # byebug
	# require 'json'
	
	# load_and_authorize_resource
	# GET /exams
	# GET /exams.json
	# byebug
	def index

		@resource =	User.find_by_authentication_token(params[:auth_token])
		# byebug
		return invalid_user unless @resource
		@exams = Exam.all
		# @user = current_user
	end

	# GET /exams/1
	# GET /exams/1.json
	def show

		@resource =	User.find_by_authentication_token(params[:auth_token])
		return invalid_user unless @resource
		@exam = Exam.find(params[:id])

		return cannot_find_exam unless @exam
			
		# end
	end

	def answer
		# byebug
		@resource =	User.find_by_authentication_token(params[:auth_token])
		return invalid_user unless @resource


		@question = Question.where(:id => "#{params[:question_id]}").first
		return invalid_question unless @question.present?

		@topic = @question.subtopic.topic

		topic_id =	@question.subtopic.topic.id
		return there_no_topic unless topic_id

		#check if user has for the topic if yes, desplay the questions, or else say they haven't paid yet.
		#Except Admins! :-) Like a boss!
		if @resource.is_admin? #the boss sees it all
			@answer = @question.response.answer
			return no_answer unless @answer
		elsif @topic.sample?
			@answer = @question.response.answer
		elsif	@resource.owns? topic_id
			@answer = @question.response.answer
			return no_answer unless @answer
		else
			return you_dont_own_topic 
		end
		
		unless @resource.has_admin_previlages?
			log_question_activity @resource, "#{@resource.first_name} clicked on this question"
		end
	end

	# GET /exams/new
	
	private

	def log_question_activity resource, note
		@activity = QuestionActivity.new
		@activity.user_id = resource.id
		@activity.question_id = params[:question_id]
		@activity.note = note
		@activity.time = Time.now
		@activity.save
	end

	def there_no_topic
		render json: { success: false, error: "This question has no topic" }, status: :unprocessable_entity
	end

	def you_dont_own_topic 
		render json: { success: false, sample: false, error: "Error you don't own this topic"}, status: :unauthorized
	end

	def no_question
		render json: { success: false, error: "that question was not found" }, status: :unprocessable_entity
	end

	def no_answer
		render json: { success: false, error: "No answer for this question" }, status: :unprocessable_entity
	end


	def ensure_param_exists(param)
		return unless params[param].blank?
		render json:{ success: false, error: "Missing #{param} parameter"}, status: :unprocessable_entity
	end

	def ensure_token_exists
		ensure_param_exists :auth_token
	end

	def ensure_question_id_exists
		ensure_param_exists :question_id
	end

	def ensure_authentication_token_param_exists
		ensure_param_exists :authentication_token
	end

	def invalid_question
		render json: { success: false, error: "Cannot find that question"}, status: :unauthorized
	end

	def cannot_find_exam
		render json: { success: false, error: "Cannot find that exam "}, status: :unauthorized
	end

	def invalid_user
		render json: { success: false, error: "Error with your credentials"}, status: :unauthorized
	end

	def set_csrf_header
		 response.headers['X-CSRF-Token'] = form_authenticity_token
	end

		# Use callbacks to share common setup or constraints between actions.
		def set_unit
			@unit = Unit.includes(:topics).find(params[:id]) #include(:topics) includes all teh topics in that unit pre-emptively, saving alot ot memory and computing resources
		end

		# Use callbacks to share common setup or constraints between actions.
		def set_exam
			@exam = Exam.includes(:questions).find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def exam_params
			params.require(:exam).permit(:title, :date, :unit_id, 
				questions_attributes:[ :id, :question, :exam_id,	:_destroy,
				response_attributes:[:id, :answer, :question_id, :video,:_destroy]]
				)
		end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
   # byebug
  require 'json'
  
  # load_and_authorize_resource
  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
    # @user = current_user
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
    @exam = Exam.find(params[:id])
    @current_user = current_user
  end

  # GET /exams/new
  def new

    @exam = Exam.new
    # @exam.questions.build
      # 1.times do
        @exam.questions.build.build_response
      # end
  end

  # GET /exams/1/edit
  def edit
     @exam = Exam.find(params[:id])
     # @exam.questions.build
     # @exam.questions.build.build_response
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def accept_tos
    # @exam = Exam.find(params[:id])
    
     @user = User.find(current_user.id)

     @user.agree_tos #(terms_params)
    # redirect_to new_exam_path
    # puts "hahaha"
   redirect_to new_exam_path, notice: 'You have accepted The terms of Service.'
  end

   def download
    #{}"#{Rails.root}/uploads/topic/attachment/#{topic.id}/topic.name.pdf",
      @exam = Exam.find(params[:id])
      send_file(@exam.attachment.path,
                filename: "#{@topic.title}.pdf",
                type: "application/pdf")
    end

    # def as_json(options={})
    #   super(:only => [:questions]
    #   )
    # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.includes(:questions).find(params[:id])
    end


    def terms_params
      params.permit(:id, :terms)
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:title, :date, :unit_id, 
        questions_attributes:[ :id, :question, :exam_id,  :_destroy,
        response_attributes:[:id, :answer, :question_id, :video,:_destroy]]
        )
    end
end

app/helpers/exams_helper.rb
module ExamsHelper

	  include ActionView::Helpers::SanitizeHelper

	  def foo
	    sanitized_output = sanitize(html_input)
	  end
end

app/views/exams/_answer_fields.html.haml
.nested-fields
	%br/
	= f.label :answer, "Answer"
	= f.text_field :answer
	= f.hidden_field :_destroy
	= link_to_remove_association "Remove Answer", f

app/views/exams/_form.html.haml
= simple_form_for @exam, :html => {:multipart => true} do |f|
  - if @exam.errors.any?
    #error_explanation
      %h2= "#{pluralize(@exam.errors.count, "error")} prohibited this exam from being saved:"
      %ul
        - @exam.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :Exam_Title
    = f.text_field :title , size: 100
    =f.label :unit
    =f.select :unit_id, Unit.all.map { |u| [u.name, u.id]}
  %br/
  .field
    = f.label :date
    = f.datetime_select :date

  .field
    = f.simple_fields_for :questions do |question|
      = render "subtopics/question_fields", f: question
  %br/

  .actions
    = f.submit 'Save Changes', class: "btn btn-success pull-right"#, "pull-right"

  %br/

app/views/exams/_question_fields.html.haml
.nested-fields
	%br/
	= f.label :question, "Question"
	= link_to_remove_association "Remove Question", f, class: "label label-danger"
	
	%br/
	= f.cktext_area :question, :cols => 30, :extraPlugins => 'eqneditor',:ckeditor => { :toolbar => 'full'}
	%br/


	= f.fields_for :response do |answer|
		=render "response_fields", f: answer

app/views/exams/_response_fields.html.haml
.nested-fields
	%br/
	= f.label :response, "Answer"
	= link_to_remove_association "Remove Answer", f, class: "label label-danger"
	= f.cktext_area :answer, :cols => 10, :ckeditor => { :toolbar => 'full'}
	/ = f.label :video
	/ = f.file_field :video

app/views/exams/_table.html.haml
%table.table.table-hover
  %thead
    %tr
      %th Name
      %th Unit
      %th institution
      %th

  %tbody
    - exams.each do |exam|
      %tr
        %td= link_to exam.title, exam
        %td= exam.unit.name
        %td= exam.unit.semester.year.course.institution.name
        %td
          -if current_user && current_user.is_admin?
            = link_to 'Edit', edit_exam_path(exam), class: "label label-warning"
            = link_to 'Destroy', exam, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "label label-danger"
            / = link_to "Download", download_exam_path(exam), class: "label label-success"
          -elsif current_user && current_user.is_moderator?
            = link_to 'Edit', edit_exam_path(exam), class: "label label-warning"

app/views/exams/edit.html.haml
%h1 Editing exam

= render 'form'

= link_to 'Show', @exam
\|
= link_to 'Back', exams_path

app/views/exams/index.html.haml
= javascript_include_tag :defaults, :cache => true

%h1
	%span.label.label-default All Exams



=render "exams/table", exams: @exams






-if current_user.is_moderator? || current_user.is_admin?
	= link_to 'New Exam', new_exam_path, class: "btn btn-primary" 
-else
	=render "terms", exam: @exams

app/views/exams/new.html.haml
%h1
	%span.label.label-default New Exam

= render 'form'

= link_to 'Back', exams_path, class: "btn btn-default"

.field
	%br/

app/views/exams/show.html.haml
%h1= @exam.title


/ %p= image_tag @exam.attachment_url(:large), height: "300"

/ %p= @exam.questions.question
%ol
	-if  @exam.questions.empty?
		%p
			This Exams has no questions yet
			-if current_user.is_moderator? || current_user.is_admin?
				= link_to 'Add questions!', edit_exam_path(@exam), class: "label label-pill label-success"
	-else
		-for question in @exam.questions
			%li= raw question.question
			%ul
				/ -if current_user.has_paid? @exam.unit.id
				- if question.response.nil?
					%p
						This question has no answer yet
				-else
					= raw question.response.answer
				
					/ = question.response.video.url unless question.response.video.nil?
					/ - if question.response.video.nil?
							


				/ -else
				/ =link_to 'Pay to get the answer', api_v1_pay_path(:payment =>{ :user_id => current_user.id, :unit_id => @exam.unit.id , :package => "standard"}, :auth_token => current_user.authentication_token), method: :post, class: "btn btn-success"
				


	-if current_user.is_moderator? || current_user.is_admin?			
		= link_to 'Add questions!', edit_exam_path(@exam), class: "label label-pill label-success"

/ =link_to 'Pay to get the answer', api_v1_pay_path(:params =>{ :exam_id => @exam.id, :user_id => current_user.id}), method: :post, class: "btn btn-success"



%p= @exam.unit.name

%p
	= link_to 'Back', exams_path, class: "btn btn-default"
	-if current_user.is_moderator? || current_user.is_admin?
		.btn-group{"aria-label" => "...", :role => "group"}
			= link_to 'Edit', edit_exam_path(@exam), class: "btn btn-primary"

app/views/exams/show_vid.html.haml
-if question.response.video.nil?
	%p
		This question has no answer yet
	-else
		/ %ul
		.well
			.embed-responsive.embed-responsive-4by3
				%iframe.embed-responsive-item{:src => "#{question.response.video.url}"}